version: "3.8"

volumes:
    mariadb:
        name: mariadb
        driver: local
        driver_opts:
            device: /home/htouil/data/mariadb
            o: bind
            type: none

    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            device: /home/htouil/data/wordpress
            o: bind
            type: none

networks:
    inception:
        driver: bridge

services:
    mariadb:
        image: mariadb:htouil
        container_name: mariadb
        build: ./requirements/mariadb/.
        env_file:
         - .env
        volumes:
         - mariadb:/var/lib/mysql
        networks:
         - inception
        restart: always

    wordpress:
        image: wordpress:htouil
        container_name: wordpress
        build: ./requirements/wordpress/.
        env_file:
         - .env
        volumes:
         - wordpress:/var/www/wordpress
        networks:
         - inception
        depends_on: 
         - mariadb
        restart: always
    nginx:
        image: nginx:htouil
        container_name: nginx
        build: ./requirements/nginx/.
        env_file:
         - .env
        volumes:
         - wordpress:/var/www/wordpress
        networks:
         - inception
        ports:
         - "443:443"
        depends_on: 
         - wordpress
        restart: always 
